---
- name: Ensure codebase is writable.
  shell:
    cmd: "if [ -d {{ deploy_path_prefix }}{{ item }} ]; then chmod -R 777 {{ deploy_path_prefix }}{{ item }}; fi"
  with_sequence: start={{ [previous_build_number | int - 50, 0] | max }}  end={{ [previous_build_number | int - deploy_code.keep, 0] | max }}
  become: true
  when: "www_user != deploy_user"

- name: Delete codebases.
  file:
    name: "{{ deploy_path_prefix }}{{ item }}"
    state: absent
  with_sequence: start={{ [previous_build_number | int - 50, 0] | max }}  end={{ [previous_build_number | int - deploy_code.keep, 0] | max }}

- name: Create a tarball of the deployed codebases.
  command:
    cmd: "tar -cvf /tmp/mount_sync.tar {{ deploy_base_path }}"
  when:
    - deploy_code.mount_sync is defined
    - deploy_code.mount_sync
  run_once: true

- name: Move to final destination.
  command:
    cmd: "mv -f /tmp/mount_sync.tar {{ deploy_code.mount_sync_tarball }}"
  when:
    - deploy_code.mount_sync is defined
    - deploy_code.mount_sync
  run_once: true
