---
- name: Copy project repository.
  synchronize:
    src: "{{ _ce_deploy_build_dir }}/"
    dest: "{{ deploy_path }}"
    archive: true
    rsync_opts:
      - "--exclude=.git"

- name: Ensure project repository is readable.
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: 0755

- name: Project specific tasks.
  include_role:
    name: "deploy_code/deploy_code-{{ project_type }}"

- name: Generate additional templates.
  template:
    src: "{{ template.src }}"
    dest: "{{ deploy_path }}/{{ template.dest }}"
  with_items: "{{ deploy_code.templates }}"
  loop_control:
    loop_var: template
  when:
    - deploy_code.templates | length
    - deploy_operation == 'deploy'

- name: Create additional symlinks.
  file:
    src: "{{ link.src }}"
    dest: "{{ deploy_path }}/{{ link.dest }}"
    state: link
  with_items: "{{ deploy_code.symlinks }}"
  loop_control:
    loop_var: link
  when:
    - deploy_code.symlinks | length
