---

- name: Copy project repository.
  synchronize:
    src: "{{ _ansible_deploy_build_dir }}/"
    dest: "{{ deploy_path }}"
    archive: yes
    rsync_opts:
      - "--exclude=.git"

- name: Ensure project repository is readable.
  file: 
    path: "{{ deploy_path }}"
    state: directory
    mode: 0755

#@todo clean below up a bit.
- include_role:
    name: "deploy_code/deploy_code-drupal"
  when: 
    - ( project_type == 'drupal7' ) or ( project_type == 'drupal8' )

# - include_role:
#     name: "deploy_code/deploy_code-{{ project_type }}"
#   when: 
#     - project_type != 'drupal7'
#     - project_type != 'drupal8'

- name: Create additional symlinks.
  file:
    src: "{{ link.src }}"
    dest: "{{ deploy_path }}/{{ link.dest }}"
    state: link
  with_items: "{{ deploy_code.symlinks }}"
  loop_control:
    loop_var: link
  when: 
   - deploy_code.symlinks | length