---

- name: Copy project repository.
  synchronize:
    src: "{{ _ce_deploy_build_dir }}/"
    dest: "{{ deploy_path }}"
    archive: yes
    rsync_opts:
      - "--exclude=.git"

- name: Ensure project repository is readable.
  file: 
    path: "{{ deploy_path }}"
    state: directory
    mode: 0755

- include_role:
    name: "deploy_code/deploy_code-{{ project_type }}"
  
- name: Create additional symlinks.
  file:
    src: "{{ link.src }}"
    dest: "{{ deploy_path }}/{{ link.dest }}"
    state: link
  with_items: "{{ deploy_code.symlinks }}"
  loop_control:
    loop_var: link
  when: 
   - deploy_code.symlinks | length