---

- name: Copy project repository.
  synchronize:
    src: "{{ local_build_path }}/"
    dest: "{{ build_path }}"
    archive: yes
    rsync_opts:
      - "--chown={{ deploy_user }}:{{ deploy_user }}"
      - "--exclude=.git"
  become: yes

- include_role:
    name: "deploy_code-{{ project_type }}"