---

- set_fact:
    build_path: "{{ deploy_base_path }}/{{ project_name }}_{{ build_type }}_build_{{ build_number }}"

- name: Copy project repository.
  synchronize:
    src: "{{ local_build_path }}/"
    dest: "{{ build_path }}"
    archive: yes
    rsync_opts:
      - "--chown={{ deploy_user }}:{{ deploy_user }}"
  become: yes

- include_role:
    name: "deploy_code-{{ project_type }}"