version: "3.7"
x-ce_dev:
  registry: localhost:5000
services:
  controller:
    x-ce_dev:
      role: controller
    container_name: deploy-controller
    image: codeenigma/ce-dev-controller:1.0.0
  utility:
    x-ce_dev:
      role: utility
      ansible:
        path: ce-dev/ansible/deploy-utility.yml
      hostnames:
        - gitlab.deploy.local
        - jenkins.deploy.local
    container_name: deploy-utility
    image: codeenigma/ce-dev:1.0.0
    privileged: true
    volumes:
      - ..:/home/ce-dev/ansible-deploy
  web:
    x-ce_dev:
      ansible:
        path: ce-dev/ansible/deploy-web.yml
      hostnames:
        - www.deploy.local
    container_name: deploy-web
    image: codeenigma/ce-dev:1.0.0
  db:
    x-ce_dev:
      ansible:
        path: ce-dev/ansible/deploy-db.yml
    container_name: deploy-db
    image: codeenigma/ce-dev:1.0.0