---
- name: Clear Matomo cache.
  command:
    cmd: "{{ deploy_path }}/{{ webroot }}/console cache:clear"
    chdir: "{{ deploy_path }}/{{ webroot }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  run_once: true
