---

- name: Init docker-compose file.
  command:
    cmd: "ce-dev init --template={{ ce_dev_prebuild.compose_template }}"
    chdir: "{{ _ce_deploy_build_dir }}"

- name: Destroy containers.
  command:
    cmd: "ce-dev destroy"
    chdir: "{{ _ce_deploy_build_dir }}"