---
- name: Perform NPM steps.
  command:
    cmd: "{{ npm.executor }} {{ npm_command }}"
    working_dir: "{{ npm.working_dir }}"
  with_items: "{{ npm.commands }}"
  loop_control:
    loop_var: npm_command
  when: deploy_operation == 'deploy'
