---

- name: Take database backup.
  include_tasks: "{{ deploy_operation }}.yml"
  with_items: "{{ mysql_backup.databases }}"
  loop_control:
    loop_var: database
  when: not mysql_backup.handling == 'none'