---
# Default Drupal 8 role. This is suitable for 
# - single site
# - multisites with a single database

- import_role:
    name: _init
- import_role:
    name: code/deploy_code
- import_role:
    name: code/composer
- import_role:
    name: maintenance_mode
  vars:
    maintenance_mode:
      operation: offline
- import_role:
    name: database_backup
- import_role:
    name: code/config_generate
- import_role:
    name: database_apply
- import_role:
    name: code/live_symlink
- import_role:
    name: maintenance_mode
  vars:
    maintenance_mode:
      operation: online
- import_role:
    name: cron/cron_database_backup
- import_role:
    name: _exit
