---
- name: Check if 'lhci' is available.
  ansible.builtin.command: "which lhci"
  register: _lhci_run_check_result
  ignore_errors: true

- name: Check if 'Xvfb' is running.
  ansible.builtin.shell: "pgrep Xvfb"
  register: _lhci_run_check_xvfb_result
  ignore_errors: true
  when:
    - _lhci_run_check_result.rc == 0

- ansible.builtin.debug:
    var: _lhci_run_check_xvfb_result

- name: Set up the X display.
  ansible.builtin.shell: "Xvfb -ac :99 -screen 0 1280x1024x16 &"
  when:
    - _lhci_run_check_result.rc == 0
    - _lhci_run_check_xvfb_result.rc > 0

- name: Export the X display ID.
  ansible.builtin.shell: "export DISPLAY=:99"
  become: true
  become_user: "{{ deploy_user }}"
  when:
    - _lhci_run_check_result.rc == 0

- name: Place the 'lighthouserc.yml' config file.
  ansible.builtin.template:
    src: lighthouserc.yml.j2
    dest: "{{ deploy_path }}/lighthouserc.yml"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  when:
    - _lhci_run_check_result.rc == 0

- name: Collect test data.
  ansible.builtin.command:
    cmd: "lhci collect"
    chdir: "{{ deploy_path }}"
  when:
    - _lhci_run_check_result.rc == 0

- name: Save test data.
  ansible.builtin.command:
    cmd: "lhci upload"
    chdir: "{{ deploy_path }}"
  when:
    - _lhci_run_check_result.rc == 0
