---

- name: Take database backup.
  include_tasks: common.yml
  # vars:
  #   mysql_backup_db:
  #     database: "{{ database.database }}"
  #     user: "{{ database.user }}"
  #     credentials_file: "{{ database.credentials_file }}"
  with_items: "{{ mysql_backup.databases }}"
  loop_control:
    loop_var: database
  when: not mysql_backup.handling == 'none'