---


# Setup database names.
- set_fact:
    _mysql_build_database_name: "{{ database.database }}_{{ build_number }}"
- set_fact:
    _mysql_previous_build_database_name: "{{ database.database }}_{{ previous_build_number }}"

  # Note: we don't use the mysql_db Ansible module on purpose.
  # If database already exists, we want to fail and not override it
  # with previous build.
- name: Create new database.
  command: mysql --defaults-extra-file={{ database.credentials_file }} -e "CREATE DATABASE {{ _mysql_build_database_name }};"

- name: Populate new database.
  shell: "mysqldump --defaults-extra-file={{ database.credentials_file }} {{ _mysql_previous_build_database_name }} | mysql --defaults-extra-file={{ database.credentials_file }} {{ _mysql_build_database_name }}"
  when: previous_build_number > 0