---

- name: Grab mysql credentials.
  fetch:
    src: "{{ database.credentials_file }}"
    dest: "build/mysql_backup_credentials.ini"
    flat: yes

- set_fact:
    _mysql_build_host: "{{ lookup('ini', 'host section=client file=build/mysql_backup_credentials.ini') }}"
- set_fact:
    _mysql_build_user_name: "{{ lookup('ini', 'user section=client file=build/mysql_backup_credentials.ini') }}"
- set_fact:
    _mysql_build_password: "{{ lookup('ini', 'password section=client file=build/mysql_backup_credentials.ini') }}"

- name: Ensure dump directory exists.
  file:
    path: "{{ mysql_backup.dumps_directory }}"
    state: directory
    mode: 0700

- name: Dump existing database.
  shell: "mysqldump --defaults-extra-file={{ database.credentials_file }} {{ database.database }} | bzip2 > {{ mysql_backup.dumps_directory }}/{{ database.database }}-{{ previous_build_number }}.sql.bz2"

- set_fact:
    _build_database:
      name: "{{ database.database }}"
      user: "{{ _mysql_build_user_name }}"
      password: "{{ _mysql_build_password }}"
      host: "{{ _mysql_build_host }}"

- set_fact:
    build_databases: "{{ build_databases + [ _build_database ] }}"