---

- name: Setup Mautic cron tasks.
  cron:
    name: "{{ project_name }}_{{ build_type }}_{{ entry.job }}"
    minute: "{{ entry.minute }}"
    hour: "{{ entry.hour | default(omit) }}"
    job: "env php {{ live_symlink_dest }}/{{ webroot }}/app/console {{ entry.job }}"
  with_items: "{{ cron_mautic.entries }}"
  loop_control:
    control_var: entry