---

#@todo: To play it safe and let people manually revert db without 
# screwing the daily backup when using rolling db, we could
# add a keep mechanism for backup scripts, like for the dumps themselves.
# Nice to have more than anything.
- include_tasks: setup.yml
  vars:
    database: database
  with_items: "{{ build_databases }}"
  loop_control:
    loop_var: database