---
# Common defaults. Given the "_init" role is mandatory,
# this will ensure defaults to other roles too.
deploy_user: "deploy"
drupal:
  sites:
    - folder: "default"
      public_files: "sites/default/files"
      config_sync_directory: "config/sync"
      #config_import_command: "cim"
      config_import_command: ""
      revert_features_command: ""
      sanitize_command: "sql-sanitize"
      base_url: https://www.example.com
      force_install: false
      cron:
        - minute: "*/{{ 10 | random(start=1) }}"
          job: cron
mautic:
  image_path: "media/images"
  force_install: false
