---

- name: Register remote dump name (from database).
  set_fact:
    mysql_sync_source_dump_path: "/tmp/{{ database.source.database }}.sql.bz2"
  when: not database.source.type == 'dump'

- name: Register existing remote dump name.
  set_fact:
    mysql_sync_source_dump_path: "{{ database.source.database }}"
  when: database.source.type == 'dump'

- name: Register target dump name.
  set_fact:
    mysql_sync_target_dump_path: "/tmp/{{ database.target.database }}.sql.bz2"

- name: Get last known good build number.
  local_action:
    module: command 
    argv: 
      - "/bin/sh"
      - "{{ _ansible_deploy_base_dir }}/scripts/track-get.sh"
      - "--repo"
      - "{{ database.target.build_info.repo }}"
      - "--branch"
      - "{{ database.target.build_info.branch }}"
      - "--playbook"
      - "{{ database.target.build_info.playbook }}"
  register: mysql_sync_target_build_number
  when: database.target.type == 'rolling'

- name: Register target database name.
  set_fact:
    mysql_sync_target_database: "{{ database.target.database }}_{{ mysql_sync_target_build_number.stdout }}"
  when: database.target.type == 'rolling'

- name: Register target database name.
  set_fact:
    mysql_sync_target_database: "{{ database.target.database }}"
  when: not database.target.type == 'rolling'

- name: Take a dump from source database.
  shell: "mysqldump --defaults-extra-file={{ database.source.credentials_file }} {{ database.source.database }} | bzip2 > {{ mysql_sync_source_dump_path }}"
  delegate_to: "{{ database.source.host }}"
  when: not database.source.type == 'dump'

- name: Fetch dump file.
  fetch: 
    src: "{{ mysql_sync_source_dump_path }}"
    dest: "{{ _ansible_deploy_build_dir }}/{{ database.target.database }}.sql.bz2"
    flat: yes
  delegate_to: "{{ database.source.host }}"

- name: Copy dump file to destination.
  copy:
    src: "{{ _ansible_deploy_build_dir }}/{{ database.target.database }}.sql.bz2"
    dest: "{{ mysql_sync_target_dump_path }}"

- name: Drop target database.
  shell: "mysql --defaults-extra-file={{ database.target.credentials_file }} drop database {{ mysql_sync_target_database }}"

- name: Recreate target database.
  shell: "mysql --defaults-extra-file={{ database.target.credentials_file }} create database {{ mysql_sync_target_database }}"

- name: Repopulate database from dump.
  shell: "bzcat {{ mysql_sync_target_dump_path }} | mysql --defaults-extra-file={{ database.target.credentials_file }} {{ mysql_sync_target_database }}"
