---

- name: Ensure public files directory exists.
  file:
    path: "{{ deploy_assets_base_path }}/{{ project_name }}_{{ build_type }}_{{ site.folder }}_public_files"
    state: directory

- name: Ensure public files directory permissions.
  file:
    path: "{{ deploy_assets_base_path }}/{{ project_name }}_{{ build_type }}_{{ site.folder }}_public_files"
    state: directory
    owner: "{{ www_user }}"
    group: "{{ www_user }}"
    recurse: yes
  become: yes
  when: "www_user != deploy_user"

- name: Remove public files folder.
  file:
    path: "{{ deploy_path }}/{{ webroot }}/{{ site.public_files }}"
    state: absent

- name: Create symlink to public files.
  file:
    src: "{{ deploy_assets_base_path }}/{{ project_name }}_{{ build_type }}_{{ site.folder }}_public_files"
    dest: "{{ deploy_path }}/{{ webroot }}/{{ site.public_files }}"
    state: link

- name: Ensure private files directory exists.
  file:
    path: "{{ deploy_assets_base_path }}/{{ project_name }}_{{ build_type }}_{{ site.folder }}_private_files"
    state: directory

- name: Ensure private files directory permissions.
  file:
    path: "{{ deploy_assets_base_path }}/{{ project_name }}_{{ build_type }}_{{ site.folder }}_private_files"
    state: directory
    owner: "{{ www_user }}"
    group: "{{ www_user }}"
    recurse: yes
  become: yes
  when: "www_user != deploy_user"

# - name: Ensure public file path is set.
#   shell: "cd {{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }} &&{{ drush_bin }}-y config:set system.file file_public_path {{ site.public_files }}"

# - name: Ensure private file path is set.
#   shell: "cd {{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }} &&{{ drush_bin }}-y config:set system.file file_private_path {{ deploy_assets_base_path }}/{{ project_name }}_{{ build_type }}_{{ site.folder }}_private_files"