---

- name: Fix file permissions for settings.php.
  file:
    state: file
    path: "{{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }}/settings.php"
    owner: "{{ www_user }}"
    group: "{{ www_user }}"
  become: yes
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site
  when: 
    - www_user != deploy_user
    - previous_build_number == 0

- name: Install Drupal.
  command:
    cmd: "{{ drush_bin }} -y si"
    chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site
  when: previous_build_number == 0

- name: Apply Drupal database updates.
  command:
    cmd: "{{ drush_bin }} -y updb"
    chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site
  when: previous_build_number == 0

- name: Import configuration.
  command:
    cmd: "{{ drush_bin }} -y {{ site.config_import_command }}"
    chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site
  when: previous_build_number == 0