---

- name: Generates settings file.
  include_tasks: settings.yml
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site

- name: Install Drupal.
  shell: "cd {{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }} && {{ drush_bin }} si -y"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site
  when: previous_build_number == 0
  become: (www_user != deploy_user)
  become_user: "{{ www_user }}"

- name: Public and private files.
  include_tasks: files.yml
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site