---
- name: Ensure log directory exists.
  file:
    path: "{{ cron_matomo.log_directory }}"
    state: directory
    mode: 0700
    recurse: true

- name: Create archive script.
  template:
    src: "matomo-archive.sh.j2"
    dest: "/home/{{ deploy_user }}/{{ project_name }}-{{ build_type }}-matomo-archive.sh"
    mode: 0700

- name: Setup regular archiving.
  cron:
    name: "cron_matomo_{{ project_name }}_{{ build_type }}"
    minute: "{{ 59 | random }}"
    job: "/home/{{ deploy_user }}/{{ project_name }}-{{ build_type }}-matomo-archive.sh"
