---
- hosts: "localhost"
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure deploy scripts are presents.
      git:
        repo: "{{ ce_deploy.own_repository | default('https://github.com/codeenigma/ce-deploy.git')}}"
        dest: "{{ ce_deploy.local_dir }}"
        version: "{{ ce_deploy.own_repository_branch  | default('master') }}"
        update: yes
        accept_hostkey: yes
      become: yes
      become_user: "{{ ce_deploy.username }}"

    - name: Checkout config directory.
      git:
        repo: "{{ ce_deploy.config_repository }}"
        accept_hostkey: yes
        dest: "{{ ce_deploy.local_dir }}/config"
      become: yes
      become_user: "{{ ce_deploy.username }}"
      when: ce_deploy.config_repository is defined and ce_deploy.config_repository
    
    - name: Check if we have a config directory.
      stat:
        path: "{{ ce_deploy.local_dir }}/config"
      register: ce_deploy_config_repo

    - name: Register config repository.
      set_fact:
        ce_deploy_has_config_repo: "{{ 'yes' if ce_deploy_config_repo.stat.isdir is defined and ce_deploy_config_repo.stat.isdir else 'no' }}"

    - name: Remove defaults folders.
      file:
        path: "{{ ce_deploy.local_dir }}/{{ item }}"
        state: absent
      with_items:
        - hosts
        - ansible.cfg
      when: ce_deploy_has_config_repo

    - name: Symlink config folders to /etc/ansible.
      file:
        dest: "{{ ce_deploy.local_dir }}/{{ item }}"
        src: "{{ ce_deploy.local_dir }}/config/{{ item }}"
        state: link
      with_items:
        - hosts
        - ansible.cfg
      when: ce_deploy_has_config_repo

    - name: Create data dir.
      file:
        path: "{{ ce_deploy.local_dir }}/data"
        state: directory