---

- name: Enable maintenance mode.
  command: 
    cmd: "{{ drush_bin }} state:set system.maintenance_mode 1 --input-format=integer"
    chdir: "{{ live_symlink_dest }}/{{ webroot }}"
  become: (www_user != deploy_user)
  become_user: "{{ www_user }}"
  when:
    - previous_build_number > 0
    - project_type == 'drupal8'