---
- name: Grab mysql credentials.
  fetch:
    src: "{{ database.credentials_file }}"
    dest: "build/mysql_backup_credentials.ini"
    flat: yes

- set_fact:
    _mysql_build_host: "{{ lookup('ini', 'host section=client file=build/mysql_backup_credentials.ini') }}"

# Build credentials for the given database itself.
- set_fact:
    _mysql_build_database_name: "{{ mysql_backup_db.database }}_{{ build_number }}"
- set_fact:
    _mysql_previous_build_database_name: "{{ mysql_backup_db.database }}_{{ previous_build_number }}"
- set_fact:
    _mysql_build_user_name: "{{ mysql_backup_db.user }}_{{ build_number }}"
- set_fact:
    _mysql_build_password: "{{ lookup('password', '/tmp/{{ _mysql_build_database_name }} chars=ascii_letters') }}"
  # Note: we don't use the mysql_db Ansible module on purpose.
  # If database already exists, we want to fail and not override it
  # with previous build.
- name: Create new database.
  command: mysql --defaults-extra-file={{ database.credentials_file }} -e "CREATE DATABASE {{ _mysql_build_database_name }};"

# We append privileges instead of replacing,
# to allow this role to be looped over,
# for multisites or projects with multiple databases.
# @todo deal with host for user.
- name: Create/update mysql user.
  command: mysql --defaults-extra-file={{ database.credentials_file }} -e "GRANT ALL ON {{ _mysql_build_database_name }}.* TO '{{ _mysql_build_user_name}}'@'%' IDENTIFIED BY '{{ _mysql_build_password }}';"

- name: Populate new database.
  shell: "mysqldump --defaults-extra-file={{ database.credentials_file }} {{ _mysql_previous_build_database_name }} | mysql --defaults-extra-file={{ database.credentials_file }} {{ _mysql_build_database_name }}"
  when: previous_build_number > 0

- set_fact:
    _build_database:
      original: "{{ database }}"
      name: "{{ _mysql_build_database_name }}"
      user: "{{ _mysql_build_user_name }}"
      password: "{{ _mysql_build_password }}"
      host: "{{ _mysql_build_host }}"

- set_fact:
    build_databases: "{{ build_databases + [ _build_database ] }}"