---

- name: Revert Drupal configuration with Features.
  include_tasks: features.yml
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site

- name: Revert Drupal configuration with Ctools.
  include_tasks: ctools.yml
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site