---
# Default Matomo role.

- import_role:
    name: _init
- import_role:
    name: deploy_code
- import_role:
    name: database_backup
- import_role:
    name: config_generate
- import_role:
    name: database_apply
- import_role:
    name: live_symlink
- import_role:
    name: cache_clear/cache_clear-opcache
- import_role:
    name: cache_clear/cache_clear-matomo
- import_role:
    name: cron/cron_database_backup
- import_role:
    name: cron/cron_matomo
- import_role:
    name: _exit