---
# Default Mautic role.

- import_role:
    name: _init
- import_role:
    name: deploy_code
- import_role:
    name: composer
# - import_role:
#     name: maintenance_mode
#   vars:
#     maintenance_mode:
#       operation: offline
- import_role:
    name: database_backup
- import_role:
    name: config_generate
- import_role:
    name: database_apply
- import_role:
    name: live_symlink
# - import_role:
#     name: maintenance_mode
#   vars:
#     maintenance_mode:
#       operation: online
- import_role:
    name: cron/cron_database_backup
- import_role:
    name: cron/cron_mautic
- import_role:
    name: _exit
