---

- name: Disable maintenance mode.
  command: 
    cmd: "{{ drush_bin }} state:set system.maintenance_mode 0 --input-format=integer"
    chdir: "{{ deploy_path }}/{{ webroot }}"
  become: (www_user != deploy_user)
  become_user: "{{ www_user }}"
  when:
    - project_type == 'drupal8'